### ISSUE TITLE
sandie-go/go import paths ignore Go import path conventions

### ISSUE THREAD

**Issue by yoursunny** [cmscaltech/sandie-ndn#19]
The import paths used by `sandie-go/go` do not use fully qualified domain names as the first element of import paths. This flies in the face of the Go convention for this (that only stdlib should do this). It [breaks assumptions built into modules](https://godoc.org/golang.org/x/mod/module#CheckPath) and has a good chance of breaking code introspection tools.
To solve this problem, change import path to `github.com/cmscaltech/sandie-ndn/go`.

**Comment by cataliniordache** [comment]
Done. Thank you for pointing this out
