### ISSUE TITLE
FileMetadata is not portable

### ISSUE THREAD

**Issue by yoursunny** [cmscaltech/sandie-ndn#21]
Currently, the ft-server program is encoding `FileMetadata` structure in a non-portable manner:
https://github.com/cmscaltech/sandie-ndn/blob/66bc72d0827aae0c278d68a75da97513f3bff178/NDNc/app/benchmark/server/ft-server.cpp#L74-L85

When this structure is reinterpreted as a byte pattern, it would differ:

* on little endian and big endian machines
* on 32-bit and 64-bit machines
* on different sizing of `mode_t` and `off_t` typedefs (POSIX standard does not guarantee a particular integer size of these types)

To solve this issue, you should encode the information using NDN-TLV structure.

**Comment by yoursunny** [comment]
Please take a look at the protocol in [ndn6-file-server](https://github.com/yoursunny/ndn6-tools/blob/main/file-server.md).
I have several file server/client implementations using this protocol, including the upcoming NDN-DPDK file server.

The major differences from your current protocol are:

* Metadata packet is identified as a KeywordNameComponent "32=metadata" instead of a GenericNameComponent "META". This prevents potential clash with a file named "META".
* Metadata packet is encoded in NDN-TLV format, following RDR specification.
* There's only `mtime` (encoded as a VersionNameComponent as the component of the name), but not `ctime`.
* There's no `st_mode`. However, the directory listing response indicates whether each name is a file or a directory.

I strongly recommend adopting this protocol instead of inventing another one.
If there's a particular field not yet in ndn6-file-server protocol but has a use case in your network, please state the reasoning / use case, and I can consider adding it.

**Comment by Pesa** [comment]
This is temporary and will be changed, as I already told you in the email. Please don't report pointless issues that we're already discussing.
